#!/bin/bash
HOOK_NAMES="applypatch-msg pre-applypatch post-applypatch pre-commit prepare-commit-msg commit-msg post-commit pre-rebase post-checkout post-merge pre-receive update post-receive post-update pre-auto-gc"
PROJECT_ROOT=$(git rev-parse --show-toplevel)
PARENT_HOOKS=$PROJECT_ROOT/.git/hooks
REPLACEMENT_HOOKS=$PROJECT_ROOT/node_modules/ddts/git-hooks

for hook in $HOOK_NAMES; do
    if [ -f $REPLACEMENT_HOOKS/$hook ]; then
        # If the hook already exists, is executable, and is not a symlink
        if [ ! -h $PARENT_HOOKS/$hook -a -x $PARENT_HOOKS/$hook ]; then
            mv $PARENT_HOOKS/$hook $PARENT_HOOKS/$hook.local
        fi

        # create the symlink, overwriting the file if it exists
        ln -s -f $REPLACEMENT_HOOKS/wrapper $PARENT_HOOKS/$hook
    fi
done
